apiVersion: v1
kind: ConfigMap
metadata:
  name:  vault-enable-transit-cm
data:
  enable-transit.sh: |
    enable_transit() {
      echo "enable transit secret engine-----"
      vault secrets enable transit
      vault write -f transit/keys/cosign type="rsa-2048"
      vault policy write cosign /vault/data/cosign.hcl 
      export COSIGN_TOKEN=$(vault token create -policy=cosign -format=json | jq -r '.auth | .client_token')
    }

    vault status
    RESULT=$?
    if [ $RESULT -eq 0 ];
    then
        exit 0
    fi

    if [ $RESULT -eq 2 ];
    then
        enable_transit
        exit 0
    else
        while [$RESULT -ne 0]; do
            sleep 5s
            vault status
            RESULT=$?
        done
        enable_transit
        exit $RESULT
    fi
