apiVersion: v1
kind: ConfigMap
metadata:
  name:  vault-enable-transit-cm
data:
  enable-transit.sh: |
    export VAULT_TOKEN=$(grep -E "root_token" /vault/data/vault-auto-unseal-keys.txt | sed 's/^.*://')

    echo "enable transit secret engine-----"
    vault secrets enable transit
    vault write -f transit/keys/cosign type="rsa-2048"
    vault policy write cosign /vault/data/cosign-policy/cosign.hcl

    vault token create -policy=cosign -format=yaml > /vault/data/cosign-token.yaml