apiVersion: batch/v1
kind: Job
metadata:
  name: enable-transit
spec:
  template:
    spec:
      containers:
      - name: enable-transit
        command: 
          - /bin/bash
          - -c
          - |
            oc wait --for=condition=Ready=true -n vault pod/vault-0
            
            echo "enable secret engine transit-----"
            
            cat /vault-enable-transit/enable-transit.sh | oc exec -i -n vault vault-0 -c vault "--" sh -c "cat > /vault/data/enable-transit.sh"
            oc exec vault-0 --namespace=vault --stdin --tty -- /bin/sh /vault/data/enable-transit.sh
        image: registry.redhat.io/openshift4/ose-cli:v4.7
        volumeMounts:
        - mountPath: /vault-enable-transit
          name: vault-enable-transit
      restartPolicy: Never
      serviceAccount: vault
      volumes:
        - name: vault-enable-transit
          configMap:
            name: vault-enable-transit-cm
